# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 21:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublesgame',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='singlesgame',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
