# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foos', '0003_player_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='name',
        ),
    ]
