# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foos', '0004_auto_20170124_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlesgame',
            name='player1_end_rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='singlesgame',
            name='player1_start_rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='singlesgame',
            name='player2_end_rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='singlesgame',
            name='player2_start_rating',
            field=models.IntegerField(default=1000),
        ),
    ]
