# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foos', '0005_auto_20170124_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublesgame',
            name='team1_end_rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='doublesgame',
            name='team1_start_rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='doublesgame',
            name='team2_end_rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='doublesgame',
            name='team2_start_rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='player',
            name='doubles_draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='singles_draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
