# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foos', '0006_auto_20170124_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='loses',
            new_name='losses',
        ),
    ]
