# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 03:08
from __future__ import unicode_literals

import math

from django.db import migrations


def reverse_losses(apps, schema_editor):
    Player = apps.get_model('foos', 'Player')
    for player in Player.objects.all():
        player.singles_losses = math.fabs(player.singles_losses)
        player.doubles_losses = math.fabs(player.doubles_losses)
        player.save()

    Team = apps.get_model('foos', 'Team')
    for team in Team.objects.all():
        team.losses = math.fabs(team.losses)
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foos', '0007_auto_20170125_1219'),
    ]

    operations = [
        migrations.RunPython(reverse_losses),
    ]
